spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/usercenter
    username: root
    password: 1234
  session:
    timeout: 86400
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag  # 全局逻辑删除字段名
      logic-delete-value: 1  # 逻辑已删除值
      logic-not-delete-value: 0  # 逻辑未删除值